version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - ./public:/app/public
      - ./logs:/app/logs
    networks:
      - app_network

  # nginx servisini kaldırıyorum çünkü Plesk zaten nginx kullanıyor
  # ve portlar çakışıyor

networks:
  app_network:
    driver: bridge