version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    # Eğer MSSQL bağlantınız varsa, network tanımlaması ekleyin
    # networks:
    #   - app_network

# networks:
#   app_network:
#     driver: bridge 