version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=localhost
      - PORT=3000
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 